#pragma once

// From GLCORE3.h
#define GLCORE_MOUSE_BUTTON_1         0
#define GLCORE_MOUSE_BUTTON_2         1
#define GLCORE_MOUSE_BUTTON_3         2
#define GLCORE_MOUSE_BUTTON_4         3
#define GLCORE_MOUSE_BUTTON_5         4
#define GLCORE_MOUSE_BUTTON_6         5
#define GLCORE_MOUSE_BUTTON_7         6
#define GLCORE_MOUSE_BUTTON_8         7
#define GLCORE_MOUSE_BUTTON_LAST      GLCORE_MOUSE_BUTTON_8
#define GLCORE_MOUSE_BUTTON_LEFT      GLCORE_MOUSE_BUTTON_1
#define GLCORE_MOUSE_BUTTON_RIGHT     GLCORE_MOUSE_BUTTON_2
#define GLCORE_MOUSE_BUTTON_MIDDLE    GLCORE_MOUSE_BUTTON_3